name: Week12
version: 0.0.0

ghc-options: -Wall

dependencies:
 - base == 4.*
 - MonadRandom == 0.5.*
 - random == 1.*

library:
  source-dirs: src

executables:
  risk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Week12

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: Week12
