name: Week8
version: 0.0.0

ghc-options: -Wall

dependencies:
 - base == 4.*
 - containers == 0.6.*

library:
  source-dirs: src

executables:
  party-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Week8

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: Week8
