name:                tien
version:             0.1.0.0
github:              "githubuser/tien"
license:             BSD3
author:              "Tien"
maintainer:          "tienlindev@gmail.com"
copyright:           "2019 Tien"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tien#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- containers
- directory

library:
  source-dirs: src

executables:
  tien-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tien

tests:
  tien-test:
    main:                PartySpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tien
